create table "public"."reports" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "created_by" uuid,
    "game_id" uuid not null,
    "reason" character varying not null
);


alter table "public"."reports" enable row level security;

CREATE UNIQUE INDEX reports_pkey ON public.reports USING btree (id);

alter table "public"."reports" add constraint "reports_pkey" PRIMARY KEY using index "reports_pkey";

alter table "public"."reports" add constraint "reports_created_by_fkey" FOREIGN KEY (created_by) REFERENCES accounts(id) ON DELETE CASCADE not valid;

alter table "public"."reports" validate constraint "reports_created_by_fkey";

alter table "public"."reports" add constraint "reports_game_id_fkey" FOREIGN KEY (game_id) REFERENCES games(id) ON DELETE CASCADE not valid;

alter table "public"."reports" validate constraint "reports_game_id_fkey";

create policy "Enable insert for all users"
on "public"."reports"
as permissive
for insert
to public
with check (true);



